# Render Blueprint
services:
  - type: web
    name: bento-microservices
    env: node
    rootDir: bento-microservices-express
    buildCommand: pnpm install --no-frozen-lockfile --prod=false && pnpm exec prisma generate && pnpm exec prisma db push --accept-data-loss && pnpm seed && pnpm build
    startCommand: pnpm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080
      - key: HOST
        value: 0.0.0.0
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URL
        sync: false
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: CLOUDINARY_FOLDER
        value: social-network-500bros
      - key: CDN_URL
        value: https://five00bros-social-network.onrender.com/uploads
