import type { Metadata } from 'next';
import React from 'react';

import { HOST_API } from '@/global-config';
import AppProviders from '@/providers/app-provider';

import './globals.css';

//-----------------------------------------------------------------------------------------------

export const metadata: Metadata = {
  title: 'Social Network',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Temporary debug to show API URL on mobile
  console.log('DEBUG INFO:');
  console.log(
    '- Hostname:',
    typeof window !== 'undefined' ? window.location.hostname : 'server'
  );
  console.log(
    '- Is Localhost?',
    typeof window !== 'undefined'
      ? window.location.hostname === 'localhost'
      : 'server'
  );
  console.log('- Env NETWORK_API:', process.env.NEXT_PUBLIC_NETWORK_API_DOMAIN);
  console.log('- Env LOCAL_API:', process.env.NEXT_PUBLIC_API_DOMAIN);
  console.log('- Final HOST_API:', HOST_API);

  return (
    <html lang="en">
      <head>
        <link
          rel="preload"
          href="/_next/static/css/app/layout.css"
          as="style"
        />
      </head>
      <body className="min-h-screen block relative bg-cushion h-full w-full before:fixed before:inset-0">
        <AppProviders>{children}</AppProviders>
      </body>
    </html>
  );
}
