version: '3'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-bento
    restart: always
    ports:
      - '3307:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=12345678
      - MYSQL_DATABASE=social_network
    volumes:
      - social_mysql:/var/lib/mysql
    networks:
      - social
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      timeout: 20s
      retries: 10
  redis:
    image: redis:6.0
    container_name: redis
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis-bento:/data
    environment:
      - REDIS_PASSWORD=macdogiahuy_redis
    networks:
      - social
    command: /bin/sh -c 'redis-server --appendonly yes --requirepass $$REDIS_PASSWORD'

networks:
  social:

volumes:
  social_mysql:
  redis-bento:
